### ISSUE TITLE
The dependency ofxSoundManager doesn't seem to exist

### ISSUE THREAD

**Issue by betamax** [martial/CorruptVideo#1]
Firstly, great work on this, it's a really cool project.

I'm trying to get the app running on my machine and have so far managed to get most of it working. However, the dependency you list as 'ofxSoundManager' doesn't seem to exist. I've Googled it and the only place Google has found that references it is your app itself.

Is the ofxSoundManager your own code? If so, would you be willing to release it?

Thanks,

Max

**Comment by martial** [comment]
Hi,

Thanks - can you try with this ? 

Just add it to addons folder and it should compile properly !

········································
Martial Geoffre-Rouland
forme-libre.com
+33 (6) 73 05 55 12

**Comment by betamax** [comment]
Apologies, I don't seem to see any attachments or anything with this message?

Thanks,

Max

**Comment by robincwillis** [comment]
Hi, also wanted to say awesome project. I am also looking for this dependency and running into the same problem as betamax.

**Comment by robincwillis** [comment]
Oh snap, I just found it here under a different name.
https://github.com/martial/ofxEQ
